# Generated by Django 4.0.3 on 2022-04-07 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_phoneotp'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneotp',
            name='validated',
            field=models.BooleanField(default=False, help_text='If it is true, that means user have validate otp correctly in secon API'),
        ),
    ]
